'use client';

import { useState, useEffect } from 'react';
import Navbar from "../navbar/page";
import { createClient } from '@/utils/supabase/client';
import { User } from '@supabase/supabase-js';

const TermsPage = () => {
  const [user, setUser] = useState<User | null>(null);
  const [loading, setLoading] = useState(true);
  const supabase = createClient();

  useEffect(() => {
    const fetchUser = async () => {
      const { data } = await supabase.auth.getUser();
      if (data?.user) {
        setUser(data.user);
      }
      setLoading(false);
    };
    fetchUser();
  }, []);

  if (loading) return null;

  const sections = [
    {
      title: '1. Service Agreement',
      content: [
        'By submitting samples to the UC Berkeley DNA Sequencing Facility, you agree to the following terms and conditions. These terms govern the use of all sequencing services provided by the facility, including Sanger sequencing, fragment analysis, DNA quantification, and related services.',
        'The facility reserves the right to refuse service if samples do not meet the required quality standards or if the submission does not comply with the guidelines outlined in our Sample Guidelines.',
        'All users must have a valid UC Berkeley account or an approved external account to submit orders. Users are responsible for ensuring the accuracy of all information provided during the order submission process.',
      ],
    },
    {
      title: '2. Payment Terms',
      content: [
        'Internal UC Berkeley users will be charged via campus recharge (chartstring). External academic and commercial users will be invoiced upon completion of services. Payment is due within 30 days of invoice date.',
        'Pricing is subject to change. Current pricing is listed on our Pricing page. Users will be notified of any pricing changes at least 30 days in advance.',
        'Failure to provide a valid chartstring or payment method may result in suspension of services. Disputed charges must be reported within 60 days of the invoice date.',
      ],
    },
    {
      title: '3. Sample Handling',
      content: [
        'The facility will handle all submitted samples with reasonable care. However, we cannot guarantee the preservation of samples during or after the sequencing process. Remaining sample material may be discarded 30 days after results are delivered unless alternative arrangements are made in advance.',
        'Users are responsible for retaining backup copies of all submitted DNA samples. The facility is not responsible for the replacement of samples that are consumed during the sequencing process or damaged due to circumstances beyond our control.',
        'Samples containing hazardous materials must be clearly labeled and accompanied by the appropriate safety documentation. The facility reserves the right to refuse samples that pose a safety risk.',
      ],
    },
    {
      title: '4. Data Privacy',
      content: [
        'All sequencing data generated by the facility is treated as confidential. Results are made available only to the submitting user and authorized members of their laboratory group.',
        'Sequencing data is stored on secure university servers and retained for a period of 90 days after delivery. After this period, data may be archived or deleted. Users are responsible for downloading and backing up their results within this timeframe.',
        'The facility will not share sequencing data with third parties without the explicit written consent of the submitting user, except as required by university policy or applicable law.',
      ],
    },
    {
      title: '5. Limitation of Liability',
      content: [
        'The UC Berkeley DNA Sequencing Facility provides services on an as-is basis. While we strive to deliver high-quality results, we do not guarantee the success of every sequencing reaction. Factors such as sample quality, template complexity, and secondary structures can affect results.',
        'The facility\'s liability is limited to re-running failed reactions at no additional charge, subject to availability of remaining sample material. The facility is not liable for indirect, incidental, or consequential damages arising from the use of our services.',
        'In no event shall the total liability of the facility exceed the amount paid by the user for the specific service in question.',
      ],
    },
    {
      title: '6. Modifications',
      content: [
        'The UC Berkeley DNA Sequencing Facility reserves the right to modify these terms and conditions at any time. Changes will be posted on this page with an updated effective date. Continued use of our services after changes are posted constitutes acceptance of the revised terms.',
        'Users are encouraged to review these terms periodically. For questions regarding these terms, please contact the facility at sequencing@berkeley.edu.',
      ],
    },
  ];

  return (
    <>
      <Navbar profilePicUrl={user?.user_metadata?.avatar_url || user?.user_metadata?.picture || ""} user={user} />
      <div className="min-h-screen bg-gray-50">
        {/* Header */}
        <div className="bg-[#003262] text-white py-12">
          <div className="max-w-4xl mx-auto px-6">
            <h1 className="text-3xl md:text-4xl font-bold">Terms &amp; Conditions</h1>
            <p className="mt-3 text-[#FDB515] text-lg">UC Berkeley DNA Sequencing Facility</p>
            <p className="mt-2 text-gray-300 text-sm">Last updated: March 2026</p>
          </div>
        </div>

        {/* Content */}
        <div className="max-w-4xl mx-auto px-6 py-10">
          <div className="bg-white rounded-lg shadow-sm border border-gray-200 p-8">
            <p className="text-gray-600 mb-8 leading-relaxed">
              Please read these terms and conditions carefully before using the services provided by the UC Berkeley DNA Sequencing Facility. By submitting samples or placing orders, you acknowledge that you have read, understood, and agree to be bound by these terms.
            </p>

            {sections.map((section, index) => (
              <div key={index} className="mb-8 last:mb-0">
                <h2 className="text-xl font-semibold text-[#003262] mb-4 border-b border-gray-200 pb-2">
                  {section.title}
                </h2>
                {section.content.map((paragraph, pIndex) => (
                  <p key={pIndex} className="text-gray-700 leading-relaxed mb-3 last:mb-0">
                    {paragraph}
                  </p>
                ))}
              </div>
            ))}

            <div className="mt-10 pt-6 border-t border-gray-200">
              <p className="text-gray-500 text-sm">
                If you have any questions about these terms, please contact us at{' '}
                <a href="mailto:sequencing@berkeley.edu" className="text-[#003262] underline hover:text-[#FDB515]">
                  sequencing@berkeley.edu
                </a>.
              </p>
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

export default TermsPage;
